// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import Foundation
import PackageDescription

// Do not edit the checksums manually! They are automatically updated by the luau.yml workflow.
// <AUTO-GENERATED-BEGIN>
let version = "0.1.0+0.690"
let luauAstChecksum = "a56599332903342e60f91e4af8d541d83cd7215163e04b93bad53ad683ba42d2"
let luauVMChecksum = "23d9bf33854640c0726ff8b1a0e443498fac4cd24b19293ea5449ab4ef0b2f8b"
let luauCompilerChecksum = "e51540542e35a9f38052ffb68488db7b1cec06ba1e1c34d42bfe3e8cf6de6897"
// <AUTO-GENERATED-END>

let localLuaAvailable = FileManager.default.fileExists(atPath: ".build/luau_build")
let localLibraries: [Target] = [
    .binaryTarget(
        name: "LuauAst",
        path: ".build/luau_build/LuauAst.xcframework"
    ),
    .binaryTarget(
        name: "LuauVM",
        path: ".build/luau_build/LuauVM.xcframework"
    ),
    .binaryTarget(
        name: "LuauCompiler",
        path: ".build/luau_build/LuauCompiler.xcframework"
    ),
]
let remoteBaseURL = "https://github.com/RadiusDay/SwiftLuau/releases/download/\(version)"
let remoteLibraries: [Target] = [
    .binaryTarget(
        name: "LuauAst",
        url: "\(remoteBaseURL)/LuauAst.xcframework.zip",
        checksum: luauAstChecksum
    ),
    .binaryTarget(
        name: "LuauVM",
        url: "\(remoteBaseURL)/LuauVM.xcframework.zip",
        checksum: luauVMChecksum
    ),
    .binaryTarget(
        name: "LuauCompiler",
        url: "\(remoteBaseURL)/LuauCompiler.xcframework.zip",
        checksum: luauCompilerChecksum
    ),
]

let package = Package(
    name: "SwiftLuau",
    platforms: [
        .macOS(.v15)
    ],
    products: [
        .library(
            name: "SwiftLuau",
            targets: ["SwiftLuau"]
        ),
        .executable(
            name: "Example",
            targets: ["Example"]
        ),
    ],
    targets: (localLuaAvailable ? localLibraries : remoteLibraries) + [
        .target(
            name: "SwiftLuauBindings",
            dependencies: ["LuauVM", "LuauAst", "LuauCompiler"],
        ),
        .target(
            name: "SwiftLuau",
            dependencies: ["SwiftLuauBindings"],
            publicHeadersPath: "include",
            linkerSettings: [
                .linkedLibrary("c++")
            ]
        ),
        .executableTarget(
            name: "Example",
            dependencies: ["SwiftLuau"],
            resources: [
                .copy("Resources/luaApp.luau")
            ]
        ),
    ]
)
