// swift-tools-version: 6.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import Foundation
import PackageDescription

// Do not edit the checksums manually! They are automatically updated by the luau.yml workflow.
// <AUTO-GENERATED-BEGIN>
let version = "0.2.2+0.694"
let luauAstChecksum = "c52cfdf678781640364b9bfb370fca0b98ddd9abf5a7ffe9366377f04ae939fe"
let luauVMChecksum = "2fb3654ce497a30a6bc981c344c07236747f3c435cf13012e22bc3a292d0e385"
let luauCompilerChecksum = "b722021d8846f5da2a39f30b5b28b49a9ed9d7058adb5c2767d88dc34320a011"
// <AUTO-GENERATED-END>

let localLuaAvailable = FileManager.default.fileExists(atPath: ".build/luau_build")
let localLibraries: [Target] = [
    .binaryTarget(
        name: "LuauAst",
        path: ".build/luau_build/LuauAst.xcframework"
    ),
    .binaryTarget(
        name: "LuauVM",
        path: ".build/luau_build/LuauVM.xcframework"
    ),
    .binaryTarget(
        name: "LuauCompiler",
        path: ".build/luau_build/LuauCompiler.xcframework"
    ),
]
let remoteBaseURL = "https://github.com/RadiusDay/SwiftLuau/releases/download/\(version)"
let remoteLibraries: [Target] = [
    .binaryTarget(
        name: "LuauAst",
        url: "\(remoteBaseURL)/LuauAst.xcframework.zip",
        checksum: luauAstChecksum
    ),
    .binaryTarget(
        name: "LuauVM",
        url: "\(remoteBaseURL)/LuauVM.xcframework.zip",
        checksum: luauVMChecksum
    ),
    .binaryTarget(
        name: "LuauCompiler",
        url: "\(remoteBaseURL)/LuauCompiler.xcframework.zip",
        checksum: luauCompilerChecksum
    ),
]

let package = Package(
    name: "SwiftLuau",
    platforms: [
        .macOS(.v15)
    ],
    products: [
        .library(
            name: "SwiftLuau",
            targets: ["SwiftLuau"]
        ),
        .executable(
            name: "Example",
            targets: ["Example"]
        ),
    ],
    targets: (localLuaAvailable ? localLibraries : remoteLibraries) + [
        .target(
            name: "SwiftLuauBindings",
            dependencies: ["LuauVM", "LuauAst", "LuauCompiler"],
        ),
        .target(
            name: "SwiftLuau",
            dependencies: ["SwiftLuauBindings"],
            publicHeadersPath: "include",
            linkerSettings: [
                .linkedLibrary("c++")
            ]
        ),
        .executableTarget(
            name: "Example",
            dependencies: ["SwiftLuau"],
            resources: [
                .copy("Resources/luaApp.luau")
            ]
        ),
    ]
)
