name: "Build"
"on":
    pull_request: null
    push: null
    workflow_dispatch: null
permissions:
    contents: "write"
jobs:
    build:
        runs-on: "macos-15"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  submodules: true
            - name: "Setup Xcode version"
              uses: "maxim-lobanov/setup-xcode@v1.6.0"
              with:
                  xcode-version: "16.3"
            - name: "Build Luau"
              run: "$GITHUB_WORKSPACE/scripts/build.sh"
            - name: "Build"
              run: "swift build --configuration release"
