name: "Build"
"on":
    pull_request: null
    push: null
    workflow_dispatch: null
permissions:
    contents: "write"
jobs:
    macos:
        runs-on: "macos-latest"
        strategy:
            matrix:
                build-system: [xcode, native]
        name: "macOS (${{ matrix.build-system }})"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  submodules: true
            - name: "Setup Xcode version"
              uses: "maxim-lobanov/setup-xcode@v1.6.0"
              with:
                  xcode-version: "16.3"
            - name: "Log Swift version"
              run: "swift --version"
            - name: "Run"
              run: "swift run --configuration release --build-system ${{ matrix.build-system }}"
    other:
        strategy:
            matrix:
                os: [{ name: "windows", runs-on: "windows-latest" }, { name: "linux (ubuntu)", runs-on: "ubuntu-latest" }]
        name: "${{ matrix.os.name }}"
        runs-on: "${{ matrix.os.runs-on }}"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  submodules: true
            - uses: SwiftyLab/setup-swift@latest
            - name: "Log Swift version"
              run: "swift --version"
            - name: "Run"
              run: "swift run --configuration release"
