name: "Build"
"on":
    pull_request: null
    push: null
    workflow_dispatch: null
permissions:
    contents: "write"
jobs:
    macos:
        runs-on: "macos-latest"
        strategy:
            matrix:
                build-system: [xcode, native]
        name: "macOS (${{ matrix.build-system }})"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  submodules: true
            - name: "Setup Xcode version"
              uses: "maxim-lobanov/setup-xcode@v1.6.0"
              with:
                  xcode-version: "16.3"
            - name: "Log Swift version"
              run: "swift --version"
            - name: "Run"
              run: "swift run --configuration release --build-system ${{ matrix.build-system }}"
    linux:
        name: "ubuntu"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  submodules: true
            - uses: SwiftyLab/setup-swift@latest
            - name: "Log Swift version"
              run: "swift --version"
            - name: "Install requirements"
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libc++-dev libc++abi-dev
            - name: "Run"
              run: "swift run --configuration release"
    windows:
        name: "windows"
        runs-on: "windows-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  submodules: true
            - uses: SwiftyLab/setup-swift@latest
            - name: "Log Swift version"
              run: "swift --version"
            - name: "Run"
              run: "swift run --configuration release"
